name = "author-companion"
pages_build_output_dir = "public"
compatibility_date = "2025-01-15"

[[d1_databases]]
binding = "DB"
database_name = "author-companion-db"
database_id = "ad222c52-772c-4124-8cd4-3c068aa262e8"
